# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Carz4Hire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'AFNetworking', '~> 2.5'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'IQKeyboardManager'
pod 'Stripe'
  # Pods for Carz4Hire

  target 'Carz4HireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Carz4HireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
